examples/rails52/config/routes.rb
Rails.application.routes.draw do
  root "bees#index"
  resources :bees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

examples/rails52/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

examples/rails52/app/models/bee.rb
class Bee < ApplicationRecord
end

examples/rails52/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

examples/rails52/app/controllers/bees_controller.rb
class BeesController < ApplicationController
  before_action :set_bee, only: [:show, :edit, :update, :destroy]

  # GET /bees
  # GET /bees.json
  def index
    @bees = Bee.all
  end

  # GET /bees/1
  # GET /bees/1.json
  def show
  end

  # GET /bees/new
  def new
    @bee = Bee.new
  end

  # GET /bees/1/edit
  def edit
  end

  # POST /bees
  # POST /bees.json
  def create
    @bee = Bee.new(bee_params)

    respond_to do |format|
      if @bee.save
        format.html { redirect_to @bee, notice: 'Bee was successfully created.' }
        format.json { render :show, status: :created, location: @bee }
      else
        format.html { render :new }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bees/1
  # PATCH/PUT /bees/1.json
  def update
    respond_to do |format|
      if @bee.update(bee_params)
        format.html { redirect_to @bee, notice: 'Bee was successfully updated.' }
        format.json { render :show, status: :ok, location: @bee }
      else
        format.html { render :edit }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bees/1
  # DELETE /bees/1.json
  def destroy
    @bee.destroy
    respond_to do |format|
      format.html { redirect_to bees_url, notice: 'Bee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bee
      @bee = Bee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bee_params
      params.require(:bee).permit(:name)
    end
end

examples/rails52/app/helpers/bees_helper.rb
module BeesHelper
end

examples/rails52/app/views/bees/_form.html.erb
<%= form_with(model: bee, local: true) do |form| %>
  <% if bee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bee.errors.count, "error") %> prohibited this bee from being saved:</h2>

      <ul>
      <% bee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

examples/rails52/app/views/bees/edit.html.erb
<h1>Editing Bee</h1>

<%= render 'form', bee: @bee %>

<%= link_to 'Show', @bee %> |
<%= link_to 'Back', bees_path %>

examples/rails52/app/views/bees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bees.each do |bee| %>
      <tr>
        <td><%= bee.name %></td>
        <td><%= link_to 'Show', bee %></td>
        <td><%= link_to 'Edit', edit_bee_path(bee) %></td>
        <td><%= link_to 'Destroy', bee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bee', new_bee_path %>

examples/rails52/app/views/bees/new.html.erb
<h1>New Bee</h1>

<%= render 'form', bee: @bee %>

<%= link_to 'Back', bees_path %>

examples/rails52/app/views/bees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bee.name %>
</p>

<%= link_to 'Edit', edit_bee_path(@bee) %> |
<%= link_to 'Back', bees_path %>

examples/rails52/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Honeycomb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>